# Phundament nano

php:
  image: schmunk42/thatsme
  command: sh src/run.sh
  links:
    - 'percona:DB'
  volumes:
    - /app

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'
  ports:
    - 8023
  volumes_from:
    - php

percona:
  image: percona:5.6
  environment:
    MYSQL_ROOT_PASSWORD: secretadmin
